id: 01a9fd9e5c9d4cbab98c1c42de0411e7
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_127-The_King_of_Samadhis_Sutra-v1
  language: en
  author: ''
  volume: {}
